# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_contract.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'order_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_contract.proto\x12\x12OrderStatusChanged\"k\n\"OrderStatusChangedIntegrationEvent\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x34\n\x0borderStatus\x18\x02 \x01(\x0e\x32\x1f.OrderStatusChanged.OrderStatus*B\n\x0bOrderStatus\x12\t\n\x05_None\x10\x00\x12\x0b\n\x07\x43reated\x10\x01\x12\x0c\n\x08\x41ssigned\x10\x02\x12\r\n\tCompleted\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERSTATUS']._serialized_start=153
  _globals['_ORDERSTATUS']._serialized_end=219
  _globals['_ORDERSTATUSCHANGEDINTEGRATIONEVENT']._serialized_start=44
  _globals['_ORDERSTATUSCHANGEDINTEGRATIONEVENT']._serialized_end=151
# @@protoc_insertion_point(module_scope)
