# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basket_contract.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'basket_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61sket_contract.proto\x12\x0f\x42\x61sketConfirmed\"\xbd\x01\n\x1f\x42\x61sketConfirmedIntegrationEvent\x12\x10\n\x08\x62\x61sketId\x18\x01 \x01(\t\x12)\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x18.BasketConfirmed.Address\x12$\n\x05items\x18\x03 \x03(\x0b\x32\x15.BasketConfirmed.Item\x12\x37\n\x0e\x64\x65liveryPeriod\x18\x04 \x01(\x0b\x32\x1f.BasketConfirmed.DeliveryPeriod\"Z\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0e\n\x06street\x18\x03 \x01(\t\x12\r\n\x05house\x18\x04 \x01(\t\x12\x11\n\tapartment\x18\x05 \x01(\t\"R\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06goodId\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"*\n\x0e\x44\x65liveryPeriod\x12\x0c\n\x04\x66rom\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x42\x1aZ\x18queues/basketconfirmedpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basket_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030queues/basketconfirmedpb'
  _globals['_BASKETCONFIRMEDINTEGRATIONEVENT']._serialized_start=43
  _globals['_BASKETCONFIRMEDINTEGRATIONEVENT']._serialized_end=232
  _globals['_ADDRESS']._serialized_start=234
  _globals['_ADDRESS']._serialized_end=324
  _globals['_ITEM']._serialized_start=326
  _globals['_ITEM']._serialized_end=408
  _globals['_DELIVERYPERIOD']._serialized_start=410
  _globals['_DELIVERYPERIOD']._serialized_end=452
# @@protoc_insertion_point(module_scope)
